version: "3.7"

volumes:
  postgresql-data:
    external: true
  nginx:
    external: true

services:
  living-postgresql:
    image: postgres:12.2-alpine
    container_name: living-postgresql
    restart: on-failure
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - PGDATA=/var/lib/postgresql/data
      - TZ=Asia/Shanghai # Set up the time zone
      - PGTZ=Asia/Shanghai # Set up the time zone
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - $PWD/docker-data/etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"

  living-adminer:
    image: adminer
    container_name: living-adminer
    restart: on-failure
    environment:
      ADMINER_DEFAULT_SERVER: living-postgresql
    depends_on:
      - living-postgresql
    ports:
      - "8080:8080"

  living-nestjs:
    build:
      context: ./nestjs
      dockerfile: $PWD/nestjs/Dockerfile
    container_name: living-nestjs
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development # Set up the environment
      - TYPEORM_HOST=living-postgresql
    ports:
      - "3600:3600"
    restart: on-failure
